<?php
/***************************************************************************
 *                          lang_faq.php [French]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id: lang_faq.php 3208 2002-12-18 15:40:21Z psotfx $
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

/***************************************************************************
 *                         Translation: Informations
 *
 *   Version: 1.0.2
 *   Date: 07/03/2008 20:44:45
 *   Author: Xaphos (Maël Soucaze)
 *   Website: http://www.phpbb.fr/
 *
 ***************************************************************************/

/* CONTRIBUTORS:
	2002-12-15	Philip M. White (pwhite@mailhaven.com)
		Fixed many minor grammatical problems.
*/
 
// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//
 
  
$faq[] = array("--","Problèmes de connexion et d’inscription");
$faq[] = array("Pourquoi ne puis-je pas me connecter ?", "Êtes-vous inscrit ? Sérieusement, vous devez être inscrit avant de pouvoir vous connecter. Avez-vous été banni du forum ? Un message apparaîtra et vous en informera. Si vous l’êtes, vous devriez contacter le webmaster ou l’administrateur du forum afin de lui demander pourquoi. Si vous êtes inscrit, que vous n’êtes pas banni et que vous n’arrivez toujours pas à vous connecter, alors vérifiez scrupuleusement le nom d’utilisateur et le mot de passe que vous avez saisi. Si vous continuez à rencontrer tout de même ce problème, veuillez contacter l’administrateur, il se peut qu’il ai mal configuré le forum.");
$faq[] = array("Pourquoi ai-je besoin de m’inscrire, après tout ?", "Vous pouvez ne pas le faire, il appartient à l’administrateur du forum d’exiger ou non que vous soyez inscrit afin de pouvoir publier des messages. Cependant, l’inscription vous donnera accès à des fonctionnalités supplémentaires qui ne sont pas disponibles aux visiteurs, comme les avatars personnalisés, la messagerie privée, l’envoi d’e-mail aux autres utilisateurs, l’adhésion à un groupe d’utilisateurs, etc. Cela ne vous prend qu’un court instant et nous vous recommandons par conséquence de le faire.");
$faq[] = array("Pourquoi suis-je déconnecté automatiquement ?", "Si vous ne cochez pas la case <span class='italic'>Me connecter automatiquement lors de chaque visite</span> lors de votre connexion au forum, vous ne resterez connecté que pour une période prédéfinie. Cette prévention empêche l’utilisation de votre compte par une personne malveillante. Pour rester connecté, cochez cette case lors de votre connexion, mais ce n’est pas recommandé si vous accédez au forum par un ordinateur public, par exemple dans une librairie, un cybercafé, une université, etc.");
$faq[] = array("Comment puis-je empêcher l’apparition de mon nom d’utilisateur dans la liste des utilisateurs en ligne ?", "Vous trouverez dans votre profil l’option <span class='italic'>Masquer mon statut en ligne</span> ; si vous réglez celle-ci sur <span class='italic'>Activé</span>, vous n’apparaîtrez qu’aux administrateurs du forum ou à vous-même. Vous serez alors compté en tant qu’utilisateur invisible.");
$faq[] = array("J’ai perdu mon mot de passe !", "Pas de panique ! Bien que votre mot de passe ne puisse pas être récupéré, il peut facilement être réinitialisé. Rendez-vous sur la page de connexion et cliquez sur <span class='underline'>J’ai perdu mon mot de passe</span>. Suivez les instructions et vous devriez pouvoir vous connecter de nouveau.");
$faq[] = array("Je suis inscrit mais ne peux pas me connecter !", "Premièrement, vérifiez votre nom d’utilisateur et votre mot de passe. S’ils sont corrects, alors une des deux choses suivantes a pu s’être produite. Si le support de la COPPA est activé et que vous avez spécifié avoir en dessous de 13 ans pendant l’inscription, vous devrez suivre les instructions que vous avez reçues. Certains forums exigeront également que les nouvelles inscriptions doivent être activées, par vous-même ou par un administrateur, avant que vous puissiez ouvrir une session ; cette information était affichée pendant l’inscription. Si un e-mail vous a déjà été envoyé, suivez les instructions. Si vous n’avez pas reçu d’e-mail, vous avez pu avoir spécifié une adresse e-mail incorrecte ou l’e-mail a pu avoir été considéré comme un courrier indésirable. Si vous êtes certain que l’adresse de e-mail spécifiée est correcte, essayez de contacter un administrateur.");
$faq[] = array("Je m’étais déjà inscrit mais ne peux plus me connecter à présent ?!", "Essayez de retrouver l’e-mail qui vous a été envoyé lorsque vous vous êtes inscrit pour la première fois, vérifiez votre nom d’utilisateur et votre mot de passe et réessayez. Il est possible qu’un administrateur ait désactivé ou ait supprimé votre compte pour une certaine raison. Beaucoup de forums suppriment périodiquement les utilisateurs qui n’ont rien publiés depuis un certain temps afin de réduire la taille de la base de données. Si tel était le cas, inscrivez-vous à nouveau et essayez de participer plus activement aux discussions.");


$faq[] = array("--","Préférences et réglages des utilisateurs");
$faq[] = array("Comment puis-je modifier mes réglages ?", "Si vous êtes un utilisateur inscrit, tous vos réglages sont stockés dans la base de données du forum. Pour les modifier, rendez-vous sur votre <span class='underline'>Profil</span> ; ce lien se situe en haut de toutes les pages du forum. Cela vous permettra de modifier tous vos réglages.");
$faq[] = array("L’heure n’est pas correcte !", "Il est possible que l’heure affichée soit réglée sur un fuseau horaire différent de celui dans lequel vous êtes. Si tel était le cas, rendez-vous sur votre profil et modifiez le fuseau horaire afin de trouver votre zone adéquate, par exemple Londres, Paris, New York, Sydney, etc. Veuillez noter que la modification du fuseau horaire, comme la plupart des réglages, n’est accessible qu’aux utilisateurs inscrits. Si vous n’êtes pas inscrit, c’est le moment idéal de le faire.");
$faq[] = array("J’ai modifié le fuseau horaire et l’heure n’est toujours pas correcte !", "Si vous êtes certain d’avoir réglé le fuseau horaire et l’heure d’été correctement mais que l’heure est encore erronée, il se peut que ce soit alors l’heure d’été qui est active alors que vous êtes en heure d’hiver, ou le contraire. Essayez de trouver la bonne heure en ajoutant ou en enlevant une heure, car phpBB2 ne supporte pas les heures spéciales.");
$faq[] = array("Ma langue n’apparaît pas dans la liste !", "Soit l’administrateur n’a pas installé votre langue, soit personne n’a encore traduit phpBB dans votre langue. Essayez de demander à l’administrateur du forum s’il peut installer le pack de langue que vous désirez. Si le pack de langue n’existe pas, vous êtes libre de vous porter volontaire afin de créer une nouvelle traduction. Pour plus d’informations, veuillez vous rendre sur le site de phpBB.com (voir le lien situé en bas des pages du forum).");
$faq[] = array("Comment puis-je afficher une image sous mon nom d’utilisateur ?", "Il y a deux images qui peuvent apparaître sous un nom d’utilisateur lors de la consultation des messages. La première peut être une image associée à votre rang, généralement en forme d’étoiles, de carrés ou de ronds, qui indiquent le nombre de messages à votre actif ou votre statut sur le forum. La seconde, habituellement une plus grande image, est connue en tant qu’avatar et est généralement unique ou personnelle à chaque utilisateur. C’est à l’administrateur du forum d’activer les avatars et de décider de la manière dont ils sont mis à disposition. Si vous ne pouvez pas utiliser d’avatars, contactez l’administrateur du forum et demandez-lui pour quelles raisons a t’il prit la décision de désactiver cette fonctionnalité.");
$faq[] = array("Comment puis-je modifier mon rang ?", "Les rangs, qui apparaissent en dessous de votre nom d’utilisateur, indiquent le nombre de messages que vous avez publiés ou identifient certains utilisateurs, comme les modérateurs et les administrateurs. Dans la plupart des cas, vous ne pouvez pas directement modifier le texte des rangs du forum car ils sont réglés par l’administrateur du forum. Veuillez ne pas abuser en publiant inutilement des messages seulement afin d’augmenter votre rang sur le forum. Beaucoup de forums ne toléreront pas cela, et un modérateur ou un administrateur abaissera votre compteur de messages.");
$faq[] = array("Lorsque je clique sur le lien de l’e-mail d’un utilisateur, il m’est demandé de me connecter ?", "Seuls les utilisateurs inscrits peuvent envoyer des e-mail aux autres utilisateurs par l’intermédiaire du formulaire e-mail intégré et seulement si l’administrateur a activé cette fonctionnalité. Cela à pour but d’empêcher toute utilisation malveillante du système e-mail par des utilisateurs anonymes ou par des agents automatisés.");


$faq[] = array("--","Problèmes de publication");
$faq[] = array("Comment puis-je publier un sujet dans un forum ?", "Pour publier un nouveau sujet dans un forum, cliquez sur le bouton adéquat situé sur l’écran du forum ou du sujet. Il se peut que vous ayez besoin d’être inscrit avant de pouvoir rédiger un message. Une liste de vos permissions sur chaque forum est disponible en bas de l’écran du forum ou du sujet. Par exemple : <span class='italic'>vous pouvez publier de nouveaux sujets</span>, <span class='italic'>vous pouvez voter dans les sondages</span>, etc.");
$faq[] = array("Comment puis-je éditer ou supprimer un message ?", "À moins que vous ne soyez un administrateur ou un modérateur du forum, vous ne pouvez éditer ou supprimer que vos propres messages. Vous pouvez éditer un message en cliquant le bouton adéquat, parfois dans une limite de temps après que le message ait été publié. Si quelqu’un a déjà répondu au message, vous trouverez un petit bout de texte en dessous du message lorsque vous revenez au sujet qui énumère le nombre de fois que vous l’avez édité, avec la date et l’heure. Ceci n’apparaîtra que si quelqu’un a effectué une réponse ; cela n’apparaîtra pas si un modérateur ou un administrateur a édité le message, bien qu’ils puissent laisser une note expliquant pourquoi ils ont édité le message. Veuillez noter que les utilisateurs normaux ne peuvent pas supprimer de message une fois que quelqu’un y a répondu.");
$faq[] = array("Comment puis-je ajouter une signature à un message ?", "Pour ajouter une signature à un message, vous devez tout d’abord en créer une par l’intermédiaire de votre profil. Une fois créée, vous pouvez cocher la case <span class='italic'>Insérer une signature</span> sur le formulaire de rédaction afin d’ajouter votre signature. Vous pouvez également ajouter une signature par défaut sur tous vos messages en cochant la case appropriée dans votre profil. Si vous faites cela, vous pouvez alors empêcher l’ajout individuel de la signature sur les messages en décochant la case d’ajout de la signature dans le formulaire de rédaction.");
$faq[] = array("Comment puis-je créer un sondage ?", "Lorsque vous rédigez un nouveau sujet ou éditez le premier message d’un sujet, vous devriez voir le formulaire <span class='italic'>Ajouter un sondage</span> en dessous du formulaire de rédaction. Si vous ne pouvez pas le voir, c’est que vous n’avez pas les permissions appropriées afin de créer des sondages. Veuillez saisir un titre pour le sondage en incluant au moins deux options. Pour cela, cliquez sur le bouton <span class='italic'>Ajouter une option</span>. Vous pouvez également régler une limite de temps en jours pour le sondage, avec 0 pour une durée illimité.");
$faq[] = array("Comment puis-je éditer ou supprimer un sondage ?", "Comme avec les messages, les sondages ne peuvent être édités que par leur auteur, un modérateur ou un administrateur. Pour éditer un sondage, éditez le premier message du sujet ; il y aura toujours le sondage associé à celui-ci. Si personne n’a voté, les utilisateurs peuvent supprimer le sondage ou éditer chaque option du sondage. Cependant, si les membres ont déjà exprimés leurs votes, seuls les modérateurs ou les administrateurs peuvent l’éditer ou le supprimer. Cela empêche les options d’un sondage à être modifiés en cours de route.");
$faq[] = array("Pourquoi ne puis-je pas accéder au forum ?", "Certains forums peuvent être limités à certains utilisateurs ou groupes d’utilisateurs. Pour consulter, lire, publier ou réaliser n’importe quelle autre action, vous avez besoin de permissions spéciales. Contactez un modérateur ou un administrateur du forum afin de demander votre accès.");
$faq[] = array("Pourquoi ne puis-je pas voter dans les sondages ?", "Seuls les utilisateurs inscrits peuvent voter dans les sondages afin de lutter contre un abus de votes. Si vous êtes inscrit et que vous ne pouvez toujours pas exprimer votre vote, il est possible que vous n’ayez pas les permissions appropriées.");


$faq[] = array("--","Mise en forme et types de sujets");
$faq[] = array("Qu’est-ce que le BBCode ?", "Le BBCode est une implémentation spéciale de l’HTML, offrant un meilleur contrôle sur la mise en forme d’un message. L’utilisation du BBCode est déterminée par l’administrateur, mais vous pouvez également le désactiver sur chacun des messages depuis le formulaire de rédaction. Le BBCode est similaire à l’architecture de l’HTML, les balises sont contenues entre des crochets [ et ] à la place de &lt; et &gt;. Pour plus d’informations à propos du BBCode, veuillez consulter le guide qui est accessible depuis la page de rédaction.");
$faq[] = array("Puis-je utiliser de l’HTML ?", "Cela dépend des permissions attribuées par l’administrateur. Si vous êtes autorisé à l’utiliser, seules certaines balises risquent de fonctionner. Ceci est une fonctionnalité de <span class='italic'>sécurité</span> afin d’éviter que les utilisateurs n’abusent des balises en déformant l’affichage d’un sujet ou à causer d’autres problèmes. Si l’HTML est activé, vous pouvez le désactiver sur chacun de vos messages depuis le formulaire de rédaction.");
$faq[] = array("Que sont les émoticônes ?", "Les émoticônes, ou smileys, sont de petites images qui peuvent être utilisées afin d’exprimer des sentiments, en utilisant un code court. Par exemple, :) exprime la joie alors que :( exprime la tristesse. La liste complète des émoticônes peut être affichée depuis le formulaire de rédaction. Essayez cependant de ne pas abuser des émoticônes, car elles peuvent rapidement rendre un message illisible et un modérateur pourrait décider de l’éditer ou de le supprimer complètement.");
$faq[] = array("Puis-je publier des images ?", "Des images peuvent être affichées dans vos messages. Cependant, il n’est pas possible de transférer directement des images à partir de votre ordinateur sur le forum. vous devez faire un lien vers une image stockée sur un serveur Internet accessible publiquement, par exemple http://www.example.com/mon-image.gif. Vous ne pouvez ni faire de lien vers des images stockées sur votre propre ordinateur (à moins que celui-ci soit un serveur Internet), ni faire de lien vers des images stockées derrière un quelconque système d’authentification, par exemple les boîtes e-mail Hotmail ou Yahoo, les sites protégés par un mot de passe, etc. Pour insérer une image, utilisez la balise BBCode [img] ou la balise HTML, si celui-ci est activé, appropriée.");
$faq[] = array("Que sont les annonces ?", "Les annonces contiennent souvent des informations importantes pour le forum dans lequel vous naviguez et vous devriez les consulter aussi vite que possible. Les annonces apparaissent en haut de chaque page du forum dans lequel elles ont été publiées. Les permissions des annonces sont définies par l’administrateur du forum.");
$faq[] = array("Que sont les notes ?", "Les notes apparaissent sous les annonces et seulement sur la première page du forum consulté. Elles sont souvent assez importantes et vous devriez les consulter dès que vous en avez l’occasion. Tout comme les annonces, les permissions des notes sont définies par l’administrateur du forum.");
$faq[] = array("Que sont les sujets verrouillés ?", "Les sujets verrouillés sont les sujets dans lesquels les utilisateurs ne peuvent plus répondre et dans lesquels les sondages sont automatiquement terminés. Les sujets peuvent être verrouillés pour de nombreuses raisons et ont été mis de cette façon par un modérateur ou un administrateur du forum.");


$faq[] = array("--","Niveaux d’utilisateurs et groupes d’utilisateurs");
$faq[] = array("Qui sont les administrateurs ?", "Les administrateurs sont des membres possédant le plus haut niveau de contrôle sur le forum. Ces utilisateurs peuvent contrôler chaque facette des opérations du forum, incluant le réglage des permissions, le bannissement d’utilisateurs, la création de groupes d’utilisateurs ou de modérateurs, etc. Ils peuvent également détenir les mêmes capacités que les modérateurs et cela dans tous les forums.");
$faq[] = array("Qui sont les modérateurs ?", "Les modérateurs sont des utilisateurs individuels (ou groupes d’utilisateurs individuels) qui surveillent jour après jour les forums. Ils ont la possibilité d’éditer ou de supprimer les sujets, les verrouiller, les déverrouiller, les déplacer, les supprimer et les diviser dans le forum qu’ils modèrent. En règle générale, les modérateurs sont présents afin d’empêcher que des utilisateurs fassent du <span class='italic'>hors-sujet</span> ou publient du contenu abusif ou offensant.");
$faq[] = array("Qui sont les groupes d’utilisateurs ?", "Les groupes d’utilisateurs sont une façon pour les administrateurs du forum de regrouper plusieurs utilisateurs. Chaque utilisateur peut appartenir à plusieurs groupes et chaque groupe peut être avoir des permissions individuelles. Cela rend les tâches plus faciles aux administrateurs car ils peuvent modifier les permissions de plusieurs utilisateurs en une seule fois, ou encore leur accorder des pouvoirs de modération, ou bien leur donner accès à un forum privé, etc.");
$faq[] = array("Comment puis-je rejoindre un groupe d’utilisateurs ?", "Pour rejoindre un groupe d’utilisateurs, cliquez sur le lien des groupes d’utilisateurs en haut du forum et vous pourrez voir tous les groupes d’utilisateurs. Tous les groupes ne sont cependant pas <span class='italic'>ouverts</span>, certains sont fermés ou ont leurs adhérents invisibles. Si le groupe est ouvert, vous pouvez le rejoindre en cliquant sur le bouton approprié. Le responsable du groupe devra approuver votre demande ; il vous demandera sans doute la raison de votre souhait. Merci de ne pas harceler un responsable de groupe s’il refuse votre demande : il doit avoir ses propres raisons.");
$faq[] = array("Comment puis-je devenir le responsable d’un groupe ?", "Le responsable du groupe est généralement assigné lorsque les groupes d’utilisateurs sont initialement créés par un administrateur du forum. Si vous êtes intéressé par la création d’un groupe d’utilisateurs, votre premier contact devrait être un administrateur ; essayez de lui envoyer un message privé.");


$faq[] = array("--","Messagerie privée");
$faq[] = array("Je ne peux pas envoyer de messages privés !", "Il y a trois raisons qui peuvent en être la cause ; soit vous n’êtes pas inscrit ou connecté, soit un administrateur a désactivé entièrement la messagerie privée sur le forum ou soit il vous empêche d’envoyer des messages privés. Si c’est le dernier cas, vous devriez demander la raison à l’administrateur du forum.");
$faq[] = array("Je continue à recevoir des messages privés non sollicités !", "Dans phpBB3, nous avons ajoutés cette fonctionnalité, mais elle n’est malheureusement pas présente dans phpBB2. Vous ne pouvez lutter contre cela qu’en avertissant l’administrateur du forum afin qu’il puisse désactiver la messagerie privée à l’utilisateur fautif.");
$faq[] = array("J’ai reçu un spam ou un e-mail non désiré de la part de quelqu’un sur ce forum !", "Nous en sommes désolés. Le formulaire d’envoi d’e-mail de ce forum possède des protections afin d’essayer de dépister les utilisateurs qui envoient de tels messages. Vous devriez envoyer par e-mail à un administrateur du forum une copie complète de l’e-mail que vous avez reçu. Il est très important que celui-ci inclut les en-têtes contenant les informations de l’auteur de l’e-mail. Il pourra alors agir en conséquence.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","Questions à propos de phpBB2");
$faq[] = array("Qui a écrit ce système de forum ?", "Ce programme (dans sa forme non modifiée) est produit, distribué et est sous copyright par le <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Il est rendu accessible sous la Licence Publique Générale GNU et peut être distribué gratuitement. Pour plus d’informations, veuillez cliquer sur le lien.");
$faq[] = array("Pourquoi la fonctionnalité X n’est pas disponible ?", "Ce programme a été écrit et mis sous licence par le phpBB Group. Si vous pensez qu’une fonctionnalité nécessite d’être ajoutée, veuillez vous rendre sur le site Internet de phpBB.com, proposez-la au phpBB Group et attendez leurs avis. Merci de ne pas envoyer directement de requêtes d’ajout de fonctionnalités sur le forum de phpBB.com, le phpBB Group utilise SourceForge afin de gérer ce type de requêtes. Veuillez consulter les forums afin de connaitre notre position, si nous en avons une, par rapport à cette fonctionnalité, et suivre la procédure spécifiée là-bas.");
$faq[] = array("Qui dois-je contacter à propos de problèmes d’abus ou d’ordres légaux liés à ce forum ?", "Vous devriez contacter l’administrateur de ce forum. Si vous ne savez pas qui s’est, demandez à un modérateur. Si vous n’obtenez aucune réponse de sa part, vous devriez alors contacter le propriétaire du domaine (faites un whois) ou, si celui-ci fonctionne sur un service gratuit (comme Yahoo!, Free.fr, f2s.com, etc.), le service de gestion des abus. Veuillez notez que le phpBB Group n’a absolument aucune juridiction et ne peut en aucun cas être tenu comme responsable de comment, où et par qui ce forum est utilisé. Ne contactez pas le phpBB Group pour tout problème d’ordre légal (commentaire incessant, insultant, diffamatoire, etc.) qui n’ont pas directement de relation avec le site Internet de phpBB.com ou le script phpBB en lui-même. Si vous envoyez un e-mail au phpBB Group à propos d’une utilisation de tierce partie de ce logiciel, attendez-vous à une réponse laconique ou à aucune réponse, tout simplement.");

//
// This ends the FAQ entries
//

?>
