<?php
/***************************************************************************
 *                          lang_faq.php [Magyar]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id: lang_faq.php,v 1.4.2.3 2002/12/18 15:40:20 psotfx Exp $
 *
 *     translated by	:  Szilard Andai
 *     web   	:  http://iranon.ezustkep.hu
 *     version	:  2.0.6
 *
 ****************************************************************************/ 

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

/* CONTRIBUTORS:
	2002-12-15	Philip M. White (pwhite@mailhaven.com)
		Fixed many minor grammatical problems.
*/

// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\";
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//

/**************************************************************************/
/*  A magyar fordítást a PHP-Nuke Magyarország csapata készítette.        */
/*  E-mail: support@php-nuke.hu                                           */
/*  Web: http://www.php-nuke.hu                                           */
/**************************************************************************/
  
$faq[] = array("--","Bel&eacute;p&eacute;si &eacute;s Regisztr&aacute;ci&oacute;s tudnival&oacute;k");
$faq[] = array("Mi&eacute;rt nem tudok bel&eacute;pni?", "Regisztr&aacute;ltad magadat? El&otilde;fordulhat, hogy a f&oacute;rum l&aacute;togat&aacute;sa regisztr&aacute;ci&oacute;hoz k&ouml;t&ouml;tt. Ki lett&eacute;l tiltva a F&oacute;rumr&oacute;l (ebben az esetben egy &uuml;zenet jelenik meg)? L&eacute;pj kapcsolatba a webmesterrel, vagy az Adminisztr&aacute;torral, hogy mi&eacute;rt tiltottak le. Ha regisztr&aacute;lva vagy, &eacute;s nem vagy kitiltva az oldalr&oacute;l, akkor ellen&otilde;rizd, hogy nem g&eacute;pelted-e el a nevet, vagy a jelsz&oacute;t. Ellen&otilde;rizd k&eacute;tszer is, mivel legt&ouml;bbsz&ouml;r ez a hiba. Ha a hiba m&eacute;g mindig fenn&aacute;ll, akkor l&eacute;pj kapcsolatba az Adminisztr&aacute;torral, megadva a hiba pontos ok&aacute;t.");
$faq[] = array("Mi&eacute;rt kell regisztr&aacute;lnom magamat?", "A regisztr&aacute;ci&oacute; nem k&ouml;telez&otilde;, ez az Adminisztr&aacute;toron m&uacute;lik, hogy sz&uuml;ks&eacute;gess&eacute; teszi-e. A regisztr&aacute;lt felhaszn&aacute;l&oacute;k t&ouml;bb szolg&aacute;ltat&aacute;shoz jutnak, melyek nem &eacute;rhet&otilde;ek el a Vend&eacute;geknek, mint p&eacute;ld&aacute;ul egy&eacute;ni Avatar k&eacute;pek, Priv&aacute;t &uuml;zenet k&uuml;ld&eacute;se, email k&uuml;ld&eacute;s, csoporttags&aacute;gok, stb. Puszt&aacute;n n&eacute;h&aacute;ny perc a regisztr&aacute;ci&oacute;, mely meg&eacute;ri a t&ouml;bb funkci&oacute; &eacute;rdek&eacute;ben.");
$faq[] = array("Mi&eacute;rt l&eacute;p ki automatikusan a rendszerb&otilde;l?", "Amennyiben a bel&eacute;p&eacute;sn&eacute;l nem jel&ouml;lted be az <span class='italic'>Automatikus bel&eacute;p&eacute;s</span> opci&oacute;t, akkor csak egy meghat&aacute;rozott ideig l&aacute;t a rendszer, mint akt&iacute;v felhaszn&aacute;l&oacute;. Ez megakad&aacute;lyozza, hogy illet&eacute;ktelenek f&eacute;rjenek hozz&aacute; az azonos&iacute;t&oacute;dhoz, vagy hogy a nevedben &iacute;rjanak a F&oacute;rumba. Nem aj&aacute;nlott az <span class='italic'>Automatikus bel&eacute;p&eacute;s</span> haszn&aacute;lata ha nyilv&aacute;nos helyr&otilde;l haszn&aacute;lod a F&oacute;rumot, mint p&eacute;ld&aacute;ul k&ouml;nyvt&aacute;r, internet k&aacute;v&eacute;z&oacute;, stb.");
$faq[] = array("Hogyan tudom megakad&aacute;lyozni, hogy m&aacute;sok l&aacute;ss&aacute;k mikor vagyok &eacute;pp jelen a F&oacute;rumon?", "A Profilban be&aacute;ll&iacute;that&oacute; egy opci&oacute;, mellyel ez letilthat&oacute;: <span class='italic'>Jelenl&eacute;t elrejt&eacute;se</span>. Ha ezt bekapcsolod, akkor csak az Adminisztr&aacute;tor, vagy saj&aacute;t magad fogod l&aacute;tni, hogy jelen vagy-e. A bekapcsol&aacute;s&aacute;val Rejtett felhaszn&aacute;l&oacute;nak sz&aacute;m&iacute;tasz.");
$faq[] = array("Elfelejtettem a jelszavamat!", "Semmi p&aacute;nik! A jelsz&oacute;t nem lehet ut&oacute;lag kider&iacute;teni, de lehet &uacute;jat k&eacute;sz&iacute;ttetni. Ehhez menj vissza a Bel&eacute;p&eacute;s oldalra, kattints az <span class='underline'>Elfelejtettem a jelsz&oacute;t</span> linkre, k&ouml;vesd az utas&iacute;t&aacute;sokat, &eacute;s r&ouml;vid id&otilde;n bel&uuml;l &uacute;jra be tudsz l&eacute;pni a F&oacute;rumba.");
$faq[] = array("Regisztr&aacute;ltam magamat, de m&eacute;gsem tudok bel&eacute;pni!", "El&otilde;sz&ouml;r ellen&otilde;rizd, hogy helyes nevet, &eacute;s jelsz&oacute;t adt&aacute;l-e meg. Ha ez rendben van, akkor k&eacute;t dolog miatt nem tudsz bel&eacute;pni. Az egyik, hogy n&eacute;h&aacute;ny f&oacute;rumon el&otilde;bb aktiv&aacute;lni kell a regisztr&aacute;ci&oacute;t, hogy be tudj l&eacute;pni. Ezt vagy neked, vagy az Adminisztr&aacute;tornak kell megtennie, m&eacute;g az els&otilde; bel&eacute;p&eacute;s el&otilde;tt. A regisztr&aacute;ci&oacute; v&eacute;g&eacute;n megtudhatod, hogy sz&uuml;ks&eacute;ges-e aktiv&aacute;lnod, a regisztr&aacute;ci&oacute;t. Az aktiv&aacute;l&aacute;s lehet email &aacute;ltal: ekkor ellen&otilde;rizd a regisztr&aacute;ci&oacute;n&aacute;l megadott emailc&iacute;medet, &eacute;s k&ouml;vesd a benne l&eacute;v&otilde; utas&iacute;t&aacute;sokat. Az aktiv&aacute;ci&oacute;ra az&eacute;rt van sz&uuml;ks&eacute;g, hogy megakad&aacute;lyozzuk a F&oacute;rum n&eacute;vtelens&eacute;g&eacute;vel vissza&eacute;l&otilde; felhaszn&aacute;l&oacute;kat. Ha biztos vagy benne, hogy &eacute;rv&eacute;nyes emailt adt&aacute;l meg, &eacute;s bel&aacute;that&oacute; id&otilde;n bel&uuml;l nem kapt&aacute;l emailt, akkor l&eacute;pj kapcsolatba az Adminisztr&aacute;torral.");
$faq[] = array("R&eacute;gebben regisztr&aacute;ltam magamat, de egy ideje nem tudok bel&eacute;pni?!", "Ennek az a leggyakoribb oka, hogy hib&aacute;s nevet, vagy jelsz&oacute;t adt&aacute;l meg (ellen&otilde;rizd az emailt, amit regisztr&aacute;l&aacute;sn&aacute;l kapt&aacute;l), vagy mert az Adminisztr&aacute;tor valami okn&aacute;l fogva t&ouml;r&ouml;lte az azonos&iacute;t&oacute;dat. Lehet hogy m&aacute;r regisztr&aacute;lva vagy, de m&eacute;g semmihez sem sz&oacute;lt&aacute;l hozz&aacute;? A F&oacute;rum bizonyos id&otilde;k&ouml;z&ouml;nk&eacute;nt t&ouml;rli azokat a felhaszn&aacute;l&oacute;kat, akik r&eacute;g&oacute;ta nem sz&oacute;ltak hozz&aacute; egy t&eacute;m&aacute;hoz sem. Regisztr&aacute;ld &uacute;jra magadat, &eacute;s kapcsol&oacute;dj be a besz&eacute;lget&eacute;sekbe.");


$faq[] = array("--","Felhaszn&aacute;l&oacute;i be&aacute;ll&iacute;t&aacute;sok");
$faq[] = array("Hogyan v&aacute;ltoztathatom meg a be&aacute;ll&iacute;t&aacute;saimat?", "Amennyiben regisztr&aacute;lt felhaszn&aacute;l&oacute; vagy, a be&aacute;ll&iacute;t&aacute;saidat a <span class='underline'>Profil</span> men&uuml;pontra kattintva &eacute;rheted el. Ez &aacute;ltal&aacute;ban az oldal tetej&eacute;n tal&aacute;lhat&oacute;, de nem minden esetben - f&uuml;gg a haszn&aacute;latban l&eacute;v&otilde; sablont&oacute;l.");
$faq[] = array("A d&aacute;tum &eacute;s/vagy id&otilde;be&aacute;ll&iacute;t&aacute;s nem pontos!", "Az id&otilde; helyesen jelenik meg, ha helyes id&otilde;z&oacute;na van be&aacute;ll&iacute;tva (Magyarorsz&aacute;g a \"GMT +1\" z&oacute;n&aacute;ba tartozik). Ezt a szolg&aacute;ltat&aacute;st csak regisztr&aacute;lt felhaszn&aacute;l&oacute;k vehetik ig&eacute;nybe.");
$faq[] = array("Megv&aacute;ltoztattam az id&otilde;z&oacute;n&aacute;t, de m&eacute;g mindig pontatlan az id&otilde;!", "Ha biztosan a helyes id&otilde;z&oacute;na van be&aacute;ll&iacute;tva, akkor feltehet&otilde;leg az&eacute;rt nem pontos, mivel probl&eacute;ma lehet a k&eacute;tfajta id&otilde;sz&aacute;m&iacute;t&aacute;s. Jelenleg a f&oacute;rum motorja nem t&aacute;mogatja a t&eacute;li-ny&aacute;ri id&otilde;sz&aacute;m&iacute;t&aacute;s v&aacute;ltoz&aacute;s&aacute;nak k&ouml;vet&eacute;s&eacute;t, &iacute;gy fordulhat el&otilde; a +-1 &oacute;ra elt&eacute;r&eacute;s az pontos id&otilde;h&ouml;z k&eacute;pest.");
$faq[] = array("A haszn&aacute;lni k&iacute;v&aacute;nt nyelv nincs a list&aacute;ban!", "Ennek az az oka, hogy az Adminisztr&aacute;tor nem telep&iacute;tett m&aacute;s nyelvet a F&oacute;rumhoz, vagy mert a F&oacute;rumhoz nincsen ford&iacute;t&aacute;s a k&iacute;v&aacute;nt nyelven. K&eacute;rd meg az Adminisztr&aacute;tort, hogy, hogy telep&iacute;tse a nyelvet a F&oacute;rumhoz, vagy ha ilyen nem l&eacute;tezik, nyugodtan k&eacute;sz&iacute;tsd el a ford&iacute;t&aacute;st. Tov&aacute;bbi inform&aacute;ci&oacute;&eacute;rt keresd fel a phpBB Csoport weboldal&aacute;t (a link az oldal alj&aacute;n tal&aacute;lhat&oacute;).");
$faq[] = array("Hogyan jelen&iacute;thetek meg egy k&eacute;pet a nevem alatt?", "A felhaszn&aacute;l&oacute;i n&eacute;v alatt k&eacute;t k&eacute;p tal&aacute;lhat&oacute;. Az egyik a Rangot mutatja (ezek &aacute;ltal&aacute;ban csillagok, vagy egy&eacute;b sorminta, melyek a hozz&aacute;sz&oacute;l&aacute;sok sz&aacute;m&aacute;nak f&uuml;ggv&eacute;ny&eacute;ben v&aacute;ltoznak). Ez alatt van egy nagyobb k&eacute;p, melyet Avatarnak nevez&uuml;nk. Az Avatar egy egyedi &eacute;s szem&eacute;lyes k&eacute;p, mely m&aacute;s &eacute;s m&aacute;s a legt&ouml;bb felhaszn&aacute;l&oacute;nak. A F&oacute;rum Adminisztr&aacute;tor&aacute;t&oacute;l f&uuml;gg, hogy lehet&otilde;s&eacute;g van-e Avatar megjelen&iacute;t&eacute;s&eacute;re. Ha nem tudsz Avatart haszn&aacute;lni, akkor az Adminisztr&aacute;tor letiltotta ezt a lehet&otilde;s&eacute;get.");
$faq[] = array("Hogyan tudom megv&aacute;ltoztatni a Rangomat?", "&Aacute;ltal&aacute;ban a felhaszn&aacute;l&oacute;k nem v&aacute;ltoztathatj&aacute;k meg k&ouml;zvetlen&uuml;l a rangot, mivel ez a hozz&aacute;sz&oacute;l&aacute;sok sz&aacute;m&aacute;t&oacute;l f&uuml;gg. Min&eacute;l t&ouml;bb hozz&aacute;sz&oacute;l&aacute;st &iacute;rsz, ann&aacute;l nagyobb lesz a rangod. A rang &aacute;ltal&aacute;ban a felhaszn&aacute;l&oacute;n&eacute;v alatt l&aacute;that&oacute; a t&eacute;m&aacute;kban. Vannak speci&aacute;lis rangok, mint p&eacute;ld&aacute;ul \"Adminsztr&aacute;tor\", vagy \"Moder&aacute;tor\". Lehet&otilde;leg ne sz&oacute;lj hozz&aacute; feleslegesen a t&eacute;m&aacute;khoz csak mert a rangodat szeretn&eacute;d n&ouml;velni: az Adminisztr&aacute;tornak &eacute;s a Moder&aacute;toroknak b&aacute;rmikor lehet&otilde;s&eacute;ge van lefokozni a rangodat, ha &uacute;gy l&aacute;tj&aacute;k j&oacute;nak.");
$faq[] = array("Mi&eacute;rt kell bejelentkezni az emailk&uuml;ld&eacute;shez?", "A F&oacute;rumon kereszt&uuml;li emailk&uuml;ld&eacute;s csak regisztr&aacute;lt felhaszn&aacute;l&oacute;k sz&aacute;m&aacute;ra lehets&eacute;ges. Ezzel a n&eacute;vtelen emberek nemk&iacute;v&aacute;nt levelez&eacute;s&eacute;nek elker&uuml;l&eacute;s&eacute;re van.");


$faq[] = array("--","Hozz&aacute;sz&oacute;l&aacute;ssal kapcsolatos k&eacute;rd&eacute;sek");
$faq[] = array("Hogyan sz&oacute;lhatok hozz&aacute; a f&oacute;rumokhoz?", "Egyszer&ucirc;, csak a megfelel&otilde; gombra kell kattintanod, mely vagy a f&oacute;rumban tal&aacute;lhat&oacute;, vagy a t&eacute;m&aacute;ban. Ha a f&oacute;rumban egy &uacute;j hozz&aacute;sz&oacute;l&aacute;st k&eacute;sz&iacute;tesz, akkor egy c&iacute;met is adj meg a t&eacute;m&aacute;nak. Ha egy m&aacute;r megnyitott t&eacute;m&aacute;ban &iacute;rsz egy &uacute;j hozz&aacute;sz&oacute;l&aacute;st, akkor nem k&ouml;telez&otilde; c&iacute;met megadni. Hozz&aacute;sz&oacute;l&aacute;s k&uuml;ld&eacute;s&eacute;hez el&otilde;bb regisztr&aacute;lnod kell magadat. A f&oacute;rum vagy a t&eacute;ma alj&aacute;n tal&aacute;lhat&oacute;ak meg a hozz&aacute;juk tartoz&oacute; jogosults&aacute;gaid (<span class='italic'>&Uacute;j t&eacute;m&aacute;t nyithat, Szavazhat, stb.</span>)");
$faq[] = array("hogyan szerkeszthetek vagy t&ouml;r&ouml;lhetek egy hozz&aacute;sz&oacute;l&aacute;st?", "Csak abban az esetben m&oacute;dos&iacute;thatsz vagy t&ouml;r&ouml;lhetsz egy hozz&aacute;sz&oacute;l&aacute;st, ha azt te k&eacute;sz&iacute;tetted, vagy ha Moder&aacute;tor, vagy a F&oacute;rum Adminisztr&aacute;tora vagy. Az <span class='italic'>&Aacute;t&iacute;r</span> gombra kattintva tudsz m&oacute;dos&iacute;tani egy hozz&aacute;sz&oacute;l&aacute;st. Ha valaki m&aacute;r v&aacute;laszolt a hozz&aacute;sz&oacute;l&aacute;sodra, abban az esetben egy r&ouml;vid megjegyz&eacute;st tal&aacute;l, hogy az h&aacute;nyszor lett m&aacute;r m&oacute;dos&iacute;tva. Ez nem jelenik meg, ha m&eacute;g senki sem v&aacute;laszolt a hozz&aacute;sz&oacute;l&aacute;sra, vagy ha a Moder&aacute;torok vagy az Adminisztr&aacute;tor szerkesztette &aacute;t. Eml&eacute;keztet&otilde;&uuml;l, a sima felhaszn&aacute;l&oacute;k nem t&ouml;r&ouml;lhetnek egy hozz&aacute;sz&oacute;l&aacute;st, melyre m&aacute;r &eacute;rkezett v&aacute;lasz.");
$faq[] = array("Hogyan csatolhatom az al&aacute;&iacute;r&aacute;somat a hozz&aacute;sz&oacute;l&aacute;shoz?", "A csatol&aacute;shoz el&otilde;sz&ouml;r el kell k&eacute;sz&iacute;tened az al&aacute;&iacute;r&aacute;st; ezt a Profilodban teheted meg. Ut&aacute;na a hozz&aacute;sz&oacute;l&aacute;sban be kell kapcsolni az <span class='italic'>Al&aacute;&iacute;r&aacute;s hozz&aacute;ad&aacute;s&aacute;t</span>. Az al&aacute;&iacute;r&aacute;s automatikusan is hozz&aacute;adhat&oacute; minden hozz&aacute;sz&oacute;l&aacute;shoz, ez szint&eacute;n a Profilban kapcsolhat&oacute; be (ha ez be van kapcsolva, ett&otilde;l f&uuml;ggetlen&uuml;l hozz&aacute;sz&oacute;l&aacute;sonk&eacute;nt m&eacute;g kikapcsolhat&oacute;).");
$faq[] = array("Hogyan k&eacute;sz&iacute;thetek szavaz&aacute;st?", "A szavaz&aacute;s k&eacute;sz&iacute;t&eacute;se egyszer&ucirc;, amikor egy &uacute;j t&eacute;m&aacute;t nyitsz, akkor ezzel egy&uuml;tt egy szavaz&aacute;st is ind&iacute;thatsz. A szavaz&aacute;s term&eacute;szetesen opcion&aacute;lis, nem k&ouml;telez&otilde; a t&eacute;manyit&aacute;shoz. Szavaz&aacute;st &uacute;gy is k&eacute;sz&iacute;thetsz, ha hozz&aacute;sz&oacute;l&aacute;sban az &Aacute;t&iacute;rra kattintasz (a m&oacute;dos&iacute;t&aacute;shoz terr&eacute;szetesen megfelel&otilde; jogokkal kell rendelkezned), &eacute;s a <span class='italic'>Szavaz&aacute;s hozz&aacute;ad&aacute;sa</span> linkre kattintassz. Megadhatsz egy c&iacute;met a szavaz&aacute;snak, &eacute;s legal&aacute;bb k&eacute;t v&aacute;laszt&aacute;si lehet&otilde;s&eacute;get &iacute;rj be (t&ouml;bb lehet&otilde;s&eacute;g be&iacute;r&aacute;s&aacute;hoz kattints a <span class='italic'>Hozz&aacute;ad&aacute;s</span> gombra. Ezenk&iacute;v&uuml;l id&otilde;limitet is megadhatsz a szavaz&aacute;shoz, mellyel megadhat&oacute;, hogy h&aacute;ny napig legyen &eacute;rv&eacute;nyes a szavaz&aacute;s. A v&aacute;laszt&aacute;si lehet&otilde;s&eacute;gek sz&aacute;ma meg van hat&aacute;rozva, melyet az Adminisztr&aacute;tor hat&aacute;roz meg.");
$faq[] = array("Hogyan szerkeszthetek vagy t&ouml;r&ouml;lhetek egy szavaz&aacute;st?", "A hozz&aacute;sz&oacute;l&aacute;sokhoz hasonl&oacute;an a szavaz&aacute;sokat is csak a szavaz&aacute;s k&eacute;sz&iacute;t&otilde;je, egy moder&aacute;tor, vagy az Adminisztr&aacute;tor szerkesztheti. Egy szavaz&aacute;s m&oacute;dos&iacute;t&aacute;s&aacute;hoz menj a t&eacute;ma els&otilde; hozz&aacute;sz&oacute;l&aacute;s&aacute;hoz (&aacute;ltal&aacute;ban ehhez tartozik a szavaz&aacute;s), &eacute;s kattints az &Aacute;t&iacute;r&aacute;s gombra. Ha senki sem szavazott az adott t&eacute;m&aacute;ban, akkor a k&eacute;sz&iacute;t&otilde;je t&ouml;r&ouml;lheti a szavaz&aacute;st; ha m&aacute;r szavaztak, akkor csak egy Moder&aacute;tor vagy az Adminisztr&aacute;tor m&oacute;dos&iacute;thatja vagy t&ouml;r&ouml;lheti.");
$faq[] = array("Mi&eacute;rt nem f&eacute;rek hozz&aacute; egyes f&oacute;rumokhoz?", "N&eacute;h&aacute;ny f&oacute;rum csak kiemelt felhaszn&aacute;l&oacute;k &eacute;s/vagy csoportok sz&aacute;m&aacute;ra hozz&aacute;f&eacute;rhet&otilde;. A f&oacute;rum megtekint&eacute;s&eacute;hez, olvas&aacute;s&aacute;hoz, hozz&aacute;sz&oacute;l&aacute;s k&uuml;ld&eacute;s&eacute;hez speci&aacute;lis enged&eacute;ly kell, amit vagy a f&oacute;rum Moder&aacute;tor&aacute;t&oacute;l vagy az Adminisztr&aacute;tort&oacute;l kaphatsz meg.");
$faq[] = array("Mi&eacute;rt nem tudok szavazni?", "Csak regisztr&aacute;lt felhaszn&aacute;l&oacute;k vehetnek r&eacute;szt a szavaz&aacute;sokban (a t&ouml;bbsz&ouml;ri szavaz&aacute;s elker&uuml;l&eacute;se v&eacute;gett). Amennyiben regisztr&aacute;lt felhaszn&aacute;l&oacute; vagy de m&eacute;gsem tudsz szavazni, akkor nincsen jogosults&aacute;god a szavaz&aacute;shoz.");


$faq[] = array("--","Form&aacute;z&aacute;s &eacute;s t&eacute;ma t&iacute;pusok");
$faq[] = array("Mi az a BBCode?", "A BBCode egy speci&aacute;lis v&aacute;ltozata a HTML nyelvnek. A BBCode haszn&aacute;lat&aacute;nak enged&eacute;lyez&eacute;se a f&oacute;rum Adminisztr&aacute;tor&aacute;t&oacute;l f&uuml;gg, de neked is lehet&otilde;s&eacute;ged van arra, hogy a hozz&aacute;sz&oacute;l&aacute;saidban ki-, vagy bekapcsold a BBCode-t. A BBCode hasonl&oacute; fel&eacute;p&iacute;t&eacute;s&ucirc;, mint a HTML, kiv&eacute;ve hogy a tagek nem kacsacs&otilde;r k&ouml;z&ouml;tt (&lt; &eacute;s &gt;), hanem sz&ouml;gletes z&aacute;r&oacute;jelben \"[\" \"]\" vannak;  amellett  lehet&otilde;s&eacute;get ny&uacute;jt hogy hogyan &eacute;s mik&eacute;nt lehet a sz&ouml;vegeket szebben, jobban, tagoltabban megjelen&iacute;teni. A haszn&aacute;latban l&eacute;v&otilde; sablont&oacute;l f&uuml;gg, hogy pontosan hol tal&aacute;lhat&oacute; meg a BBCode panel, melyr&otilde;l k&ouml;nnyed&eacute;n &eacute;s gyorsan be lehet illeszteni a tageket a sz&ouml;vegbe. Fontos, hogy mindig &uuml;gyelj&uuml;nk a tagek lez&aacute;r&aacute;s&aacute;ra. Egy r&eacute;szletesebb le&iacute;r&aacute;s tal&aacute;lhat&oacute; m&eacute;g a BBCode Gy.I.K-ban, melyet a hozz&aacute;sz&oacute;l&aacute;s k&eacute;sz&iacute;t&eacute;s&eacute;n&eacute;l tal&aacute;lsz meg.");
$faq[] = array("Haszn&aacute;lhatok HTML-t k&oacute;dot?", "Ez az Adminisztr&aacute;tort&oacute;l f&uuml;gg, &otilde; hat&aacute;rozza meg hogy lehet-e haszn&aacute;lni vagy nem. Ha enged&eacute;lyezte a haszn&aacute;lat&aacute;t, akkor is csak val&oacute;sz&iacute;n&ucirc;leg n&eacute;h&aacute;ny tag fog m&ucirc;k&ouml;dni. Ennek <span class='italic'>biztons&aacute;gi</span> okai vannak; megakad&aacute;lyozza hogy a felhaszn&aacute;l&oacute;k ak&aacute;r v&eacute;letlen&uuml;l ak&aacute;r sz&aacute;nd&eacute;kosan megv&aacute;ltoztass&aacute;k az oldal(ak) form&aacute;tum&aacute;t vagy kin&eacute;zet&eacute;t, vagy hogy egy&eacute;b probl&eacute;m&aacute;t okozzanak. A HTML k&oacute;dokat b&aacute;rki letilthatja a hozz&aacute;sz&oacute;l&aacute;s&aacute;ban.");
$faq[] = array("Mik az Emotikonok?", "Smiley-k vagy m&aacute;sn&eacute;ven Emotikonok kis grafik&aacute;k, melyekkel &eacute;rz&eacute;seket lehet kifejeztetni. P&eacute;ld&aacute;ul a :) jelent&eacute;se mosolyg&aacute;s, boldogs&aacute;g, a :( jelent&eacute;se szomor&uacute;s&aacute;g. A haszn&aacute;lhat&oacute; emotikonok teljes list&aacute;ja megtal&aacute;lhat&oacute;k a hozz&aacute;sz&oacute;l&aacute;s k&eacute;sz&iacute;t&eacute;s&eacute;n&eacute;l. Lehet&otilde;leg ne haszn&aacute;lj t&uacute;l sok emotikont, mert nehezen lesz olvashat&oacute; a hozz&aacute;sz&oacute;l&aacute;s.");
$faq[] = array("Csatolhatok k&eacute;peket a hozz&aacute;sz&oacute;l&aacute;shoz?", "Egy hozz&aacute;sz&oacute;l&aacute;sban k&eacute;peket is meg lehet jelen&iacute;ttetni, de ezt csak k&uuml;ls&otilde; webc&iacute;m megad&aacute;s&aacute;val. Jelenleg nincs lehet&otilde;s&eacute;g arra, hogy a F&oacute;rumra t&ouml;ltsd fel a k&eacute;peket. A megjelen&iacute;t&eacute;s&eacute;hez egy publikus, az interneten el&eacute;rhet&otilde; k&eacute;pet kell megadni, p&eacute;ld&aacute;ul: http://www.akarmi.hu/kep.jpg. A saj&aacute;t g&eacute;pen tal&aacute;lhat&oacute; k&eacute;peket nem lehet megjelen&iacute;teni (kiv&eacute;ve ha fut egy webszerver a g&eacute;pen, sem a v&eacute;dett oldalakon tal&aacute;lhat&oacute; k&eacute;peket (p&eacute;ld&aacute;ul lev&eacute;lfi&oacute;kokban (Hotmail, Yahoo), vagy jelsz&oacute;val v&eacute;dett oldalakon), stb. A k&eacute;p megjelen&iacute;t&eacute;s&eacute;hez haszn&aacute;ld a BBCode [img] tagj&eacute;t, vagy a megfelel&otilde; HTML taget (amennyiben ez ut&oacute;bbi enged&eacute;lyezve van).");
$faq[] = array("Mik azok a K&ouml;zlem&eacute;nyek?", "A k&ouml;zlem&eacute;nyek gyakran fontos inform&aacute;ci&oacute;kat tartalmaznak, &eacute;rdemes ezeket min&eacute;l hamarabb elolvasni. A k&ouml;zlem&eacute;nyek az adott f&oacute;rumban mindig az oldal tetej&eacute;n, az &ouml;sszes oldalon megtal&aacute;lhat&oacute;ak. Ahhoz hogy valaki k&ouml;zlem&eacute;nyt k&uuml;ldj&ouml;n, megfelel&otilde; jogokkal kell rendelkeznie, melyet az Adminisztr&aacute;tor &aacute;ll&iacute;t be.");
$faq[] = array("Mik azok a Kiemelt t&eacute;m&aacute;k?", "A kiemelt t&eacute;m&aacute;k a K&ouml;zlem&eacute;nyek alatt jelennek meg, de csak a f&oacute;rum els&otilde; oldal&aacute;n. Ezek &aacute;ltal&aacute;ban el&eacute;g fontos inform&aacute;ci&oacute;kat tartalmaznak, ez&eacute;rt aj&aacute;nlott az elolvas&aacute;sa. Hasonl&oacute;an a K&ouml;zlem&eacute;nyekhez, az Adminisztr&aacute;tor d&ouml;nti el, hogy ki &iacute;rhat Kiemelt t&eacute;m&aacute;t.");
$faq[] = array("ik azok a lez&aacute;rt t&eacute;m&aacute;k?", "A t&eacute;m&aacute;kat vagy a Moder&aacute;torok, vagy az Adminisztr&aacute;tor z&aacute;rhatja le. Az ilyen t&eacute;m&aacute;kba nem lehet t&ouml;bb hozz&aacute;sz&oacute;l&aacute;st vagy szavazatot k&uuml;ldeni. Egy t&eacute;ma lez&aacute;r&aacute;s&aacute;nak t&ouml;bb oka lehet.");


$faq[] = array("--","Felhaszn&aacute;l&oacute;i szintek &eacute;s Csoportok");
$faq[] = array("Ki az Adminisztr&aacute;tor?", "Az Adminisztr&aacute;tor a F&oacute;rum legmagasabb rang&uacute; &eacute;s jog&uacute; felhaszn&aacute;l&oacute;ja, &otilde; &uuml;zemelteti, &eacute;s tartja karban. Az eg&eacute;sz F&oacute;rumhoz hozz&aacute;f&eacute;rhet, &eacute;s m&oacute;dos&iacute;thatja, p&eacute;ld&aacute;ul jogosults&aacute;gokat adhat, letilthat felhaszn&aacute;l&oacute;kat, csoportokat hozhat l&eacute;tre, Moder&aacute;tori jogosults&aacute;gokat adhat, stb. Ezenk&iacute;v&uuml;l b&aacute;rmely f&oacute;rumot &eacute;s t&eacute;m&aacute;t moder&aacute;lhatja. Az Adminisztr&aacute;tor &aacute;ltal&aacute;ban egy szem&eacute;ly, de ez F&oacute;rumt&oacute;l f&uuml;gg, van ahol t&ouml;bben rendelkeznek ilyen jogosults&aacute;ggal.");
$faq[] = array("Kik azok a Moder&aacute;torok?", "A Moder&aacute;torok olyan k&uuml;l&ouml;nleges jogosults&aacute;gokkal rendelkez&otilde; felhaszn&aacute;l&oacute;k, akiknek az a feladata, hogy napr&oacute;l napra figyelemmel k&ouml;vess&eacute;k a f&oacute;rumok m&ucirc;k&ouml;d&eacute;s&eacute;t. Jogukban &aacute;ll b&aacute;rmely hozz&aacute;sz&oacute;l&aacute;s szerkeszt&eacute;se vagy t&ouml;rl&eacute;se, ezenk&iacute;v&uuml;l lez&aacute;rhatj&aacute;k, kinyithatj&aacute;k, &aacute;thelyezhetik, t&ouml;r&ouml;lhetik vagy sz&eacute;tv&aacute;laszthatj&aacute;k a t&eacute;m&aacute;kat, amikben moder&aacute;lhatnak. &Aacute;ltal&aacute;ban az a dolguk, hogy elt&aacute;vol&iacute;ts&aacute;k a t&eacute;m&aacute;ba nem ill&otilde; hozz&aacute;sz&oacute;l&aacute;sokat, vagy a s&eacute;rteget&otilde;, t&aacute;mad&oacute; hangv&eacute;tel&ucirc; anyagokat.");
$faq[] = array("Mik azok a Csoportok?", "Az Adminisztr&aacute;tor csoportokba rendezheti az azonos &eacute;rdekl&otilde;d&eacute;si k&ouml;r&ucirc; felhaszn&aacute;l&oacute;kat. Egy felhaszn&aacute;l&oacute; t&ouml;bb csoportba is tartozhat, &eacute;s a csoportokhoz k&uuml;l&ouml;nb&ouml;z&otilde; hozz&aacute;f&eacute;r&eacute;si jogok rendelhet&otilde;ek. Ezzel k&ouml;nnyed&eacute;n lehet p&eacute;ld&aacute;ul z&aacute;rtk&ouml;r&ucirc; f&oacute;rumokat k&eacute;sz&iacute;teni, vagy moder&aacute;tori jogokat adni egyszerre t&ouml;bb felhaszn&aacute;l&oacute;knak.");
$faq[] = array("Hogyan csatlakozhatok egy Csoporthoz?", "A Csoportok megtekint&eacute;s&eacute;hez kattints a lap tetej&eacute;n tal&aacute;lhat&oacute; Csoportok men&uuml;pontra. A link helye a haszn&aacute;lt sablont&oacute;l f&uuml;gg. Nem minden csoport &eacute;rhet&otilde; el, lehetnek <span class='italic'>ny&iacute;lt</span> csoportok, z&aacute;rt csoportok, vagy ak&aacute;r rejtett csoportok is. Ha csoport nyitott, akkor a megfelel&otilde; gombra kattintva el lehet k&uuml;ldeni a csatlakoz&aacute;si k&eacute;relmet. A csatlakoz&aacute;shoz sz&uuml;ks&eacute;ges a csoport Moder&aacute;tor&aacute;nak j&oacute;v&aacute;hagy&aacute;sa, megk&eacute;rdezheti, hogy mi&eacute;rt takarsz csatlakozni a csoportba. Ha a moder&aacute;tor elutas&iacute;tja a k&eacute;relmedet, akkor annak biztosan megvan az oka, &iacute;gy ne &otilde;t hib&aacute;ztasd.");
$faq[] = array("Hogyan lehetek Csoport Moder&aacute;tor?", "A Csoportokat az Adminisztr&aacute;tor k&eacute;sz&iacute;ti, &iacute;gy a hozz&aacute;tartoz&oacute; moder&aacute;tori jogokat is &otilde; adja ki. Ha saj&aacute;t csoportot akarsz ind&iacute;tani, akkor l&eacute;pj kapcsolatba az Adminisztr&aacute;torral, p&eacute;ld&aacute;ul egy Priv&aacute;t &uuml;zenet k&uuml;ld&eacute;s&eacute;vel.");


$faq[] = array("--","Priv&aacute;t &uuml;zenet");
$faq[] = array("Nem tudok Priv&aacute;t &uuml;zenetet k&uuml;ldeni!", "Ennek n&eacute;gy oka lehet: 1. Nem vagy regisztr&aacute;lva. 2. Nem vagy bel&eacute;pve a F&oacute;rumra. 3. az Adminisztr&aacute;tor nem enged&eacute;lyezte a F&oacute;rumon a Priv&aacute;t &uuml;zenet k&uuml;ld&eacute;s&eacute;t. 4. Nem k&uuml;ldhetsz Priv&aacute;t &uuml;zeneteket. Ha a legutols&oacute; eset &aacute;ll fenn, l&eacute;pj kapcsolatba az Adminisztr&aacute;torral.");
$faq[] = array("Folyamatosan k&eacute;retlen &uuml;zeneteket kapok!", "A j&ouml;v&otilde;ben lehet&otilde;s&eacute;g lesz letiltani a nemk&iacute;v&aacute;nt Priv&aacute;t &uuml;zeneteket. Egyel&otilde;re erre nincs lehet&otilde;s&eacute;g, ha k&eacute;retlen &uuml;zeneteket kapsz, &eacute;rtes&iacute;tsd az Adminisztr&aacute;tort, &eacute;s &otilde; megteszi a sz&uuml;ks&eacute;ges l&eacute;p&eacute;seket.");
$faq[] = array("K&eacute;retlen vagy s&eacute;rteget&otilde; leveleket kapok valakit&otilde;l a F&oacute;rumr&oacute;l!", "Ezt sajn&aacute;lattal halljuk, ebben az esetben a k&ouml;vetkez&otilde; l&eacute;p&eacute;seket tedd meg. &Eacute;rtes&iacute;tsd az Adminisztr&aacute;tort, &eacute;s k&uuml;ldd el neki a kapott levelet, els&otilde;sorban a lev&eacute;l fejl&eacute;ce sz&uuml;ks&eacute;ges (mivel ez tartalmazza a felad&oacute; adatait). Az Adminisztr&aacute;tor meg fogja tenni a sz&uuml;ks&eacute;ges l&eacute;p&eacute;seket.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","phpBB 2 k&eacute;rd&eacute;sek");
$faq[] = array("Kik k&eacute;sz&iacute;tett&eacute;k ezt a f&oacute;rumot?", "A szoftver tulajdonosa a <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. &Otilde;k foglalkoznak a kiad&aacute;ssal, fejleszt&eacute;ssel &eacute;s a szerz&otilde;i jogok is &otilde;ket illeti meg. A szoftver a GNU General Public licensz al&aacute; tartozik. Tov&aacute;bbi r&eacute;szletek a weboldalon.");
$faq[] = array("Mi&eacute;rt nem &eacute;rhet&otilde; el az X szolg&aacute;ltat&aacute;s?", "A szoftvert a phpBB Group k&eacute;sz&iacute;tette &eacute;s licenszeli. Ha &uacute;gy gondolod, hogy &uacute;jabb szolg&aacute;ltat&aacute;sok, &eacute;s opci&oacute;k sz&uuml;ks&eacute;ges a f&oacute;rumba, akkor l&aacute;togasd meg a phpbb.com weboldalt, ahol elmondhatod az &ouml;tleteidet, &eacute;szrev&eacute;teleidet. Ne k&uuml;ldj k&eacute;r&eacute;seket a phpbb.com F&oacute;rum&aacute;ba, a fejleszt&otilde;k a www.sourceforge.net oldalon v&aacute;rj&aacute;k az &ouml;tleteket. Azonk&iacute;v&uuml;l olvasd &aacute;t a F&oacute;rumot, mert lehet hogy az &ouml;tletet m&aacute;s m&aacute;r felvetette, &eacute;s m&aacute;r folyamatban van a megval&oacute;s&iacute;t&aacute;sa.");
$faq[] = array("Ki az illet&eacute;kes a F&oacute;rumon olvashat&oacute; tartalommal kapcsolatban?", "Els&otilde;sorban a F&oacute;rum Adminisztr&aacute;tor&aacute;t kell felkeresni. Ha ez nem lehets&eacute;ges, akkor a weboldal tulajdonos&aacute;t (ezt kider&iacute;theti egy &uacute;n. \"whois\" keres&eacute;ssel). Ha a f&oacute;rum egy ingyenes t&aacute;rhelyen tal&aacute;lhat&oacute;, akkor azt a szolg&aacute;ltat&oacute;t &eacute;rtes&iacute;tse. A phpBB Group-nak semmilyen k&ouml;ze, hozz&aacute;f&eacute;r&eacute;se vagy belesz&oacute;l&aacute;sa nincs a F&oacute;rumon olvashat&oacute; tartalomhoz, &eacute;s nem is &aacute;llnak kapcsolatban a szoftver &uuml;zemeltet&otilde;j&eacute;vel.");

//
// This ends the FAQ entries
//

?>